#!/bin/bash

options=$(
  getopt --name "$0" \
      --options "d:" \
      --longoptions "default:,no-default" \
      -- "$@" )

eval set -- "$options"

default="y"

while :; do
  case "$1" in
    -d|--default)
      default=$2
      shift 2
      ;;
    --no-default)
      default=""
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "$0: unhandled option -- $1" >2
      shift
      ;;
  esac
done

if [[ -z "$default" ]]; then
  selection_text="y/n"
elif [[ "${default,,}" = y* ]]; then
  selection_text="Y/n"
else
  selection_text="y/N"
fi

while
  read -p "${1-Confirm? }${1:+ }[$selection_text] " response
  [[ -z "${response:=$default}" ]]
do
  :
done

[[ "${response,,}" = y* ]]
