#!/bin/bash

options=$(
  getopt --name "$0" \
      --options "d:" \
      --longoptions "default:" \
      -- "$@" )

eval set -- "$options"

default="y"

while :; do
  case "$1" in
    -d|--default)
      default=$2
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "$0: unhandled option -- $1" >2
      shift
      ;;
  esac
done

if [[ "${default,,}" = y* ]]; then
  selection_text="Y/n"
else
  selection_text="y/N"
fi

read -p "${1-Confirm? }${1:+ }[$selection_text] " response
response=${response:-$default}
[[ "${response,,}" = y* ]]
